### ISSUE TITLE
Somehow 2020 and earlier year API queries time out

### ISSUE THREAD

**Issue by MrCsabaToth** [QuentinPhilipp/strava-3D-stats#5]
It comes back with "504 Gateway Time-out | nginx/1.18.0 (Ubuntu)"
![Screenshot_2022-06-18_19-12-32](https://user-images.githubusercontent.com/744949/174463015-772cbe2d-8ba2-4df7-b1f5-e43cac79f515.png)

**Comment by QuentinPhilipp** [comment]
That's weird, I just tried and it worked for me. Maybe you reached the request limit after a few tests. I'll have a look at the requests made and check if the threshold had been reach in the last days. 
Maybe there are unwanted calls to the API. 

I'll also add a proper error message if the API limit is reached.

**Comment by QuentinPhilipp** [comment]
I've looked at the logs and according to the error code sent by Strava, it looks like a disconnection because your access token was considered invalid. The application stores the authentication information in the server associated with a session cookie. There was a mistake in the session cookie that made it persistent in the session. If you load the page and don't close it, the session will keep the Strava connection-token. After 6h, the application will still think that the user is authenticated even if Strava revoked the API token. In this case, any new request will fail.

Do you know if this could have happened to you @MrCsabaToth? Maybe you loaded 2021 (and maybe 2022) before getting disconnected, so the data were stored in the cache on the server-side. However, all new requests were failing because a new authentication was needed.

There are two ways to solve this issue.

- The session needs to be dropped after 6h max and force the user to log in again.
- Strava has a way to refresh connection-token. I could implement a way to refresh automatically the token. With this solution, a user is always authenticated, and the cookie is persisted on the client-side.

**Comment by MrCsabaToth** [comment]
Might be rate limit. Now seeing the source code you actually gather the activities and need to aggregate the daily stats.

**Comment by MrCsabaToth** [comment]
Oh yes, I only authenticated one time, long time ago, when I gave permission to your webapp. I have a mobile app which uses Strava API (and I'm using the REST API + OAuth). When the session token expires either the app has to re-prompt for auth, or use the refresh token portion of the OAuth token to automatically extend the expiration.

**Comment by MrCsabaToth** [comment]
But this makes sense. But interestingly 2021 kinda always works, so I was not suspecting that the token would have expired, and the webapp didn't prompt about that. But even the error message is not like a 401 or 403. But I think that's what's happening probably then.

**Comment by QuentinPhilipp** [comment]
2021 will always work because it's the default year currently, so it's loaded and stored on the server directly after your first authentication. The other years requires new calls to the API.

I'm not fond of using an automatic token refresh system for client-side applications, I think it's a great feature to keep collecting user data on a server or for a different purpose, like when using webhooks to follow all the activities of an athlete. For me, the client should be disconnected when the 6h are over and the user needs to log in again. On the web version of Strava, you also need to log in again every time you go on their website. But maybe this is not very user-friendly, I don't know. What do you think?

Anyway, I need at least to prompt an error message or give more information to the user and make sure the application doesn't return a code 5XX

**Comment by QuentinPhilipp** [comment]
Should be fixed with #7
